environment:
  node_pre_gyp_accessKeyId:
    secure: cj7khL+9CvTRE8YRWCfyL1S3tK3OUCMfLGSKim8QTIk=
  node_pre_gyp_secretAccessKey:
    secure: x3Igbv0oAXCTMx+f6CKYeoXhuvdciwu+Fv3qHn3hvToGOc1wW2ET8/fRyx0100SC
  matrix:
    - nodejs_version: 0.10.40
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 0.10.40
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 0.12.7
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 0.12.7
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 1.8.1
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 1.8.1
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 2.0.0
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 2.0.0
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 3.3.0
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 3.3.0
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 4.0.0
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 4.0.0
      platform: x86
      msvs_toolset: 12
    - nodejs_version: 5.0.0
      platform: x64
      msvs_toolset: 12
    - nodejs_version: 5.0.0
      platform: x86
      msvs_toolset: 12
    # custom visual studio 2015 builds
    - nodejs_version: 0.10.40
      platform: x86
      msvs_toolset: 14
      TOOLSET_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140
    - nodejs_version: 0.10.40
      platform: x64
      msvs_toolset: 14
      TOOLSET_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140
    - nodejs_version: 0.12.7
      platform: x86
      msvs_toolset: 14
      TOOLSET_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140
    - nodejs_version: 0.12.7
      platform: x64
      msvs_toolset: 14
      TOOLSET_ARGS: --dist-url=https://s3.amazonaws.com/mapbox/node-cpp11 --toolset=v140

os: Visual Studio 2015

install:
  - scripts\build-appveyor.bat

build: OFF
test: OFF
deploy: OFF
